version: "2"
checks:
  complex-logic:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 10
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**

exclude_patterns:
  - htmlcov/*
  - dist/*
  - assets/*
  - "*.egg-info/*"
